#?regions us-east-1 us-east-2

AWSTemplateFormatVersion: 2010-09-09
Resources:
  User:
    Type: AWS::IAM::User
    Properties: 
      UserName: github-runner
  
  Key:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: 0
      Status: Active
      UserName: !Ref User

  KeyParameter:
    Type: Custom::SecureStringParameter
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-secure-string-parameter
      Name: /github/runner/credentials
      Description: Credentials for the github runner user
      Type: SecureString
      Value: !Sub |
        {"awsAccessKeyId":"${Key}","awsSecretAccessKey":"${Key.SecretAccessKey}"}