AWSTemplateFormatVersion: 2010-09-09
Parameters:
  InstanceName:
    Type: String
    Description: The name of the lightsail instance
Resources:
  InstanceKeyPair:
    Type: Custom::LightsailKeyPair
    Properties:
      ServiceToken: {Fn::ImportValue: custom-lightsail-key-pair}
      KeyPairName: !Sub "lightsail-key-pair-${InstanceName}"
  InstanceKeyPairParam:
    Type: Custom::SecureStringParameter
    Properties:
      ServiceToken: {Fn::ImportValue: custom-secure-string-parameter}
      Name: !Sub '/lightsail/${InstanceName}/private-key'
      Description: !Sub 'Private Key for the lightsail key pair for instance ${InstanceName}'
      Type: SecureString
      Value: !GetAtt [ InstanceKeyPair, PrivateKey ]
  StaticIp:
    Type: Custom::LightsailStaticIp
    Properties:
      ServiceToken: {Fn::ImportValue: custom-lightsail-static-ip}
      StaticIpName: !Sub "lightsail-static-ip-${InstanceName}"
  Instance:
    Type: Custom::LightsailInstance
    Properties:
      ServiceToken: {Fn::ImportValue: custom-lightsail-instance}
      InstanceName: !Ref InstanceName
      KeyPairName: !Ref InstanceKeyPair
      StaticIpName: !Ref StaticIp

  User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "lightsail-user-${InstanceName}"
      Tags:
        - Key: LightsailInstance
          Value: !Ref InstanceName
  UserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: 0
      UserName: !Ref User
  AccessKeyIdParam:
    Type: Custom::SecureStringParameter
    Properties:
      ServiceToken: {Fn::ImportValue: custom-secure-string-parameter}
      Name: !Sub '/lightsail/${InstanceName}/access-key-id'
      Description: !Sub 'Access Key ID for the lightsail user for instance ${InstanceName}'
      Type: SecureString
      Value: !Ref UserAccessKey
  SecretAccessKeyParam:
    Type: Custom::SecureStringParameter
    Properties:
      ServiceToken: {Fn::ImportValue: custom-secure-string-parameter}
      Name: !Sub '/lightsail/${InstanceName}/secret-access-key'
      Description: !Sub 'Secret Access Key for the lightsail user for instance ${InstanceName}'
      Type: SecureString
      Value: !GetAtt [ UserAccessKey, SecretAccessKey ]
  SecretsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'lightsail-${InstanceName}-secrets-policy'
      Description: !Sub "Grants permissions to protected elements of the ${InstanceName} Lightsail instance."
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 'ssm:GetParameters'
            Resource:
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/lightsail/${InstanceName}/private-key'
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/lightsail/${InstanceName}/access-key-id'
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/lightsail/${InstanceName}/secret-access-key'
Outputs:
  UserArn:
    Description: "Arn of the user for the lightsail instance"
    Value: !GetAtt [User, Arn]
    Export:
      Name: !Sub 'lightsail:${InstanceName}:UserArn'
  SecretsPolicyArn:
    Description: "Arn of policy for access to secrets of the lightsail instance."
    Value: !Ref SecretsPolicy
    Export:
      Name: !Sub 'lightsail:${InstanceName}:SecretsPolicyArn'