version: 0.2

env:
  shell: bash
  variables:
    BIN: ../aws-helper/bin

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 12
  
  build: 
    on-failure: ABORT
    commands:
