version: master
name: lightsail-docker-compose
default: custom-resource
deployments:
  custom-resource:
    provider: aws
    using: custom-resource
    regions:
      - us-east-1
    preBuild: |
      pushd ../.. && npm ci && popd && \
      npx tsc -b && npx ncc build src/index.ts -mo dist && cp schema.json dist && \
      cd dist && npm init -y >/dev/null
    parameters:
      Name: '{{ ref name }}'
      Runtime: nodejs14.x
      Handler: index.handler
      CodeDir: './dist'
      PolicyStatements:
        - Effect: Allow
          Action:
            - lightsail:GetInstance
          Resource: 
            Fn::Sub: arn:aws:lightsail:*:${AWS::AccountId}:*
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: 
            Fn::Sub: arn:aws:ssm:*:${AWS::AccountId}:parameter/lightsail/*/private-key
