name: Setup clou
description: Setup the clou binary
inputs: 
  version:
    description: version of the clou binary to use
    default: "latest"
outputs: {}
runs:
  using: composite
  steps:
    - id: getVersion
      shell: bash
      run: |
        VERSION="v$( echo ${{ inputs.version }} | sed s/^v//)"
        if [[ "${{ inputs.version }}" == "latest" ]]; then
          VERSION=$(curl -s https://api.github.com/repos/tjbrockmeyer/clou/releases/latest | jq -r '.tag_name')
        fi
        if [[ "$VERSION" == "null" ]]; then
          exit 1;
        fi
        echo "::set-output name=version::$VERSION"
    - shell: bash
      run: |
        echo "installing clou"
        VERSION="${{ steps.getVersion.outputs.version }}"
        if [[ "$RUNNER_OS" = "Linux" ]]; then
          EXECUTABLE="clou-linux"
        elif [[ "$RUNNER_OS" = "macOS" ]]; then
          EXECUTABLE="clou-macos"
        elif [[ "$RUNNER_OS" = "Windows" ]]; then
          EXECUTABLE="clou-win.exe"
        else
          echo "OS is unsupported: $RUNNER_OS" >&2
          exit 1
        fi
        OUT="$RUNNER_TEMP/clou/clou"
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          dest="${dest}.exe"
        fi
        mkdir "$(dirname "$OUT")"
        URL="https://github.com/tjbrockmeyer/clou/releases/download/$VERSION/$EXECUTABLE"
        echo Installing clou from $URL to $OUT
        curl -L -o "$OUT" "$URL"
        if [[ "$RUNNER_OS" != "Windows" ]]; then
          chmod +x "$OUT"
        fi
        echo "$(dirname "$OUT")" >> $GITHUB_PATH
