name: Setup clou
description: Setup the clou binary
inputs: 
  version:
    description: version of the clou binary to use
    required: true
    default: v1.0.0
outputs: {}
runs:
  using: composite
  steps:
    - name: Download and Install clou
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        EXECUTABLE="$([[ $RUNNER_OS = "Linux" ]] && printf "clou-linux" || [[ $RUNNER_OS = "macOS" ]] && printf "clou-macos" || [[ $RUNNER_OS = "Windows" ]] && printf "clou-win.exe" || "")"
        if [[ -z $EXECUTABLE ]]; then 
          echo "OS is unsupported: $RUNNER_OS" >&2
          exit 1
        fi
        OUT="$RUNNER_TEMP/clou/clou"
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          dest="${dest}.exe"
        fi
        mkdir "$(dirname "$OUT")"
        curl -L -o "$OUT"  https://github.com/tjbrockmeyer/clou/releases/download/$VERSION/$EXECUTABLE
        if [[ "$RUNNER_OS" != "Windows" ]]; then
          chmod +x "$OUT"
        fi
        echo "$(dirname "$OUT")" >> $GITHUB_PATH
