AWSTemplateFormatVersion: 2010-09-09

Parameters:
  GHACredentialsSerial:
    Type: Number
    Default: 0

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub ${AWS::AccountId}-main-bucket
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256
  BucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /global/bucket-name
      Type: String
      Value: !Ref Bucket
  
  StackNotificationsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: stack-notifications-topic
  StackNotificationsTopicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /global/stack-notifications-topic-arn
      Type: String
      Value: !Ref StackNotificationsTopic

  GHAUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: github-runner
  
  GHAKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: !Ref GHACredentialsSerial
      Status: Active
      UserName: !Ref GHAUser

  GHAKeyParameter:
    Type: Custom::SecureStringParameter
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-secure-string-parameter
      Name: /github/runner/credentials
      Description: Credentials for the github runner user
      Type: SecureString
      Value: !Sub |
        {"awsAccessKeyId":"${GHAKey}","awsSecretAccessKey":"${GHAKey.SecretAccessKey}"}
