AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Metadata:
  Substitution:
    PolicyStatements: '.Resources.Function.Properties.Policies[0].Statement'

Parameters:
  Name: 
    Type: String
  Runtime:
    Type: String
  Handler:
    Type: String

Globals:
  Function:
    Environment:
      Variables:
        PYTHONPATH: "/var/task:/var/task/site-packages:/var/runtime"

Outputs:
  FunctionArn:
    Value: !GetAtt Function.Arn
    Export:
      Name: !Sub cfn-custom-resource-${Name}

Resources:

  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub cfn-custom-resource-${Name}
      Handler: !Ref Handler
      Runtime: !Ref Runtime
      Timeout: 600
      PackageType: Zip
      CodeUri: './'
      Policies:
        - Statement: []