AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Name:
    Type: String
    Description: The name of the lightsail instance
  AccessKeySerial:
    Type: Number
    Description: The name of the lightsail instance
    Default: 0

Outputs: {}

Resources:

  InstanceKeyPair:
    Type: Custom::LightsailKeyPair
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-lightsail-key-pair
      KeyPairName: !Sub lightsail-key-pair-${Name}

  InstanceKeyPairParam:
    Type: Custom::SecureStringParameter
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-secure-string-parameter
      Name: !Sub /lightsail/${Name}/private-key
      Description: !Sub Private Key for the lightsail key pair for instance ${Name}
      Type: SecureString
      Value: !GetAtt InstanceKeyPair.PrivateKey

  StaticIp:
    Type: Custom::LightsailStaticIp
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-lightsail-static-ip
      StaticIpName: !Sub lightsail-static-ip-${Name}

  Instance:
    Type: Custom::LightsailInstance
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-lightsail-instance
      InstanceName: !Ref Name
      KeyPairName: !Ref InstanceKeyPair
      PrivateKey: !GetAtt InstanceKeyPair.PrivateKey
      AvailabilityZone: !Sub ${AWS::Region}a
      StaticIpName: !Ref StaticIp

  User: 
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref Name
      Path: '/lightsail/'
      Policies:
        - PolicyName: Inline
          PolicyDocument:
            Version: '2012-10-17'
            Statement: 
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: '*'
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: !Ref AccessKeySerial
      Status: Active
      UserName: !Ref User
  AccessKeyParameter:
    Type: Custom::SecureStringParameter
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-secure-string-parameter
      Name: !Sub /lightsail/${Name}/access-key
      Description: Access key for the linkbot user
      Value: !Sub '{"awsAccessKeyId":"${AccessKey}","awsSecretAccessKey":"${AccessKey.SecretAccessKey}"}'
  InstanceUser:
    Type: Custom::LightsailUser
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-lightsail-user
      InstanceName: !Ref Instance
      PrivateKey: !GetAtt InstanceKeyPair.PrivateKey
      AccessKeyId: !Ref AccessKey
      SecretAccessKey: !GetAtt AccessKey.SecretAccessKey
