version: master
name: teabee
default: instance
deployments:
  instance:
    provider: aws
    using: lightsail-instance
    regions:
      - us-east-1
    parameters:
      Name: '{{ ref name }}'
      BundleId: micro_2_0
      AccessKeySerial: 28
