AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Name:
    Type: String
    Description: The name of the lightsail instance
  AccessKeySerial:
    Type: Number
    Description: The name of the lightsail instance
    Default: 0

Outputs: {}

Resources:

  Instance:
    Type: AWS::Lightsail::Instance
    Properties:
      InstanceName: !Ref Name
      KeyPairName: !Ref InstanceKeyPair
      AvailabilityZone: !Sub ${AWS::Region}a
      BlueprintId: amazon_linux_2
      BundleId: nano_2_0
      UserData: |
        sudo yum update -y
        sudo yum install -y jq git

        # docker
        sudo amazon-linux-extras install docker
        sudo service docker start
        sudo usermod -a -G docker ec2-user
        # auto-start
        sudo chkconfig docker on

        # docker-compose
        sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

        # support for certbot
        sudo wget -r --no-parent -A 'epel-release-*.rpm' https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/
        sudo rpm -Uvh dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-*.rpm
        sudo yum-config-manager --enable epel*
        sudo yum repolist all
        sudo amazon-linux-extras install epel -y
        sudo yum install -y certbot

  InstanceKeyPair:
    Type: Custom::LightsailKeyPair
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-lightsail-key-pair
      KeyPairName: !Sub lightsail-key-pair-${Name}
  InstanceKeyPairParam:
    Type: Custom::SecureStringParameter
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-secure-string-parameter
      Name: !Sub /lightsail/${Name}/private-key
      Description: !Sub Private Key for the lightsail key pair for instance ${Name}
      Type: SecureString
      Value: !GetAtt InstanceKeyPair.PrivateKey
      
  StaticIp:
    Type: AWS::Lightsail::StaticIp
    Properties:
      StaticIpName: !Sub lightsail-static-ip-${Name}
      AttachedTo: !Ref Instance

  User: 
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref Name
      Path: '/lightsail/'
      Policies:
        - PolicyName: Inline
          PolicyDocument:
            Version: '2012-10-17'
            Statement: 
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: '*'
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: !Ref AccessKeySerial
      Status: Active
      UserName: !Ref User
  AccessKeyParameter:
    Type: Custom::SecureStringParameter
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-secure-string-parameter
      Name: !Sub /lightsail/${Name}/access-key
      Description: Access key for the linkbot user
      Value: !Sub '{"awsAccessKeyId":"${AccessKey}","awsSecretAccessKey":"${AccessKey.SecretAccessKey}"}'
  InstanceUser:
    DependsOn: 
      - StaticIp
      - AccessKeyParameter
      - InstanceKeyPairParam
    Type: Custom::LightsailUser
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-lightsail-user
      InstanceName: !Ref Instance
