version: master
name: lightsail-key-pair
default: custom-resource
deployments:
  custom-resource:
    provider: aws
    using: custom-resource
    regions:
      - us-east-1
    parameters:
      Name: '{{ ref name }}'
      Runtime: python3.9
      Handler: lambda_function.handler
      CodeDir: '.'
      PolicyStatements:
        - Effect: Allow
          Action:
            - lightsail:CreateKeyPair
            - lightsail:DeleteKeyPair
          Resource:
            Fn::Sub: arn:aws:lightsail:*:${AWS::AccountId}:*
