AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /global/bucket-name
  CodeVersion:
    Type: String

Globals:
  Function:
    Environment:
      Variables:
        PYTHONPATH: "/var/task/site-packages:/var/runtime"

Outputs:
  LightsailInstanceFunctionArn:
    Value: !GetAtt LightsailInstanceCustomResource.Arn
    Export:
      Name: cfn-custom-resource-lightsail-instance
  LightsailKeyPairFunctionArn:
    Value: !GetAtt LightsailKeyPairCustomResource.Arn
    Export:
      Name: cfn-custom-resource-lightsail-key-pair
  LightsailStaticIpFunctionArn:
    Value: !GetAtt LightsailStaticIpCustomResource.Arn
    Export:
      Name: cfn-custom-resource-lightsail-static-ip
  SecureStringParameterFunctionArn:
    Value: !GetAtt SecureStringParameterCustomResource.Arn
    Export:
      Name: cfn-custom-resource-secure-string-parameter
  DockerSwarmFunctionArn:
    Value: !GetAtt DockerSwarmCustomResource.Arn
    Export:
      Name: cfn-custom-resource-docker-swarm
  DockerStackFunctionArn:
    Value: !GetAtt DockerStackCustomResource.Arn
    Export:
      Name: cfn-custom-resource-docker-stack

Resources:

  LightsailInstanceCustomResource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cfn-custom-resource-lightsail-instance
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 600
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Sub code/custom-resource/lightsail-instance/${CodeVersion}.zip
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - lightsail:CreateInstances
              - lightsail:GetInstanceState
              - lightsail:GetInstance
              - lightsail:DeleteInstance
              - lightsail:AttachStaticIp
              - lightsail:DetachStaticIp
            Resource: !Sub arn:aws:lightsail:*:${AWS::AccountId}:*

  LightsailKeyPairCustomResource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cfn-custom-resource-lightsail-key-pair
      Handler: lambda_function.handler
      Runtime: python3.8
      Timeout: 600
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Sub code/custom-resource/lightsail-key-pair/${CodeVersion}.zip
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - lightsail:CreateKeyPair
              - lightsail:DeleteKeyPair
            Resource: !Sub arn:aws:lightsail:*:${AWS::AccountId}:*

  LightsailStaticIpCustomResource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cfn-custom-resource-lightsail-static-ip
      Handler: lambda_function.handler
      Runtime: python3.8
      Timeout: 600
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Sub code/custom-resource/lightsail-static-ip/${CodeVersion}.zip
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - lightsail:GetStaticIp
              - lightsail:ReleaseStaticIp
              - lightsail:GetInstanceState
              - lightsail:AttachStaticIp
              - lightsail:DetachStaticIp
              - lightsail:AllocateStaticIp
            Resource: !Sub arn:aws:lightsail:*:${AWS::AccountId}:*

  SecureStringParameterCustomResource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cfn-custom-resource-secure-string-parameter
      Handler: lambda_function.handler
      Runtime: python3.8
      Timeout: 600
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Sub code/custom-resource/secure-string-parameter/${CodeVersion}.zip
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - ssm:PutParameter
              - ssm:DeleteParameter
            Resource: !Sub arn:aws:ssm:*:${AWS::AccountId}:parameter/*

  DockerSwarmCustomResource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cfn-custom-resource-docker-swarm
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 600
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Sub code/custom-resource/docker-swarm/${CodeVersion}.zip
      Policies:
        - Statement:
          - Effect: Allow
            Action: ssm:GetParameter*
            Resource: !Sub arn:aws:ssm:*:${AWS::AccountId}:parameter/lightsail/*/private-key
          - Effect: Allow
            Action: lightsail:GetInstances
            Resource: !Sub arn:aws:lightsail:*:${AWS::AccountId}:*
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:PutParameter
              - ssm:DeleteParameter
            Resource: !Sub arn:aws:ssm:*:${AWS::AccountId}:parameter/docker-swarm/*/manager

  DockerStackCustomResource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cfn-custom-resource-docker-stack
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 600
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Sub code/custom-resource/docker-stack/${CodeVersion}.zip
      Policies:
        - Statement:
          - Effect: Allow
            Action: ssm:GetParameter*
            Resource: 
              - !Sub arn:aws:ssm:*:${AWS::AccountId}:parameter/lightsail/*/private-key
              - !Sub arn:aws:ssm:*:${AWS::AccountId}:parameter/docker-swarm/*/manager
          - Effect: Allow
            Action: lightsail:GetInstances
            Resource: !Sub arn:aws:lightsail:*:${AWS::AccountId}:*
