AWSTemplateFormatVersion: 2010-09-09

Parameters:
  InstanceName:
    Type: String
    Description: The name of the lightsail instance

Outputs:
  UserArn:
    Description: Arn of the user for the lightsail instance
    Value: !GetAtt User.Arn
    Export:
      Name: !Sub lightsail-${AWS::Region}-${InstanceName}-UserArn
  SecretsPolicyArn:
    Description: Arn of policy for access to secrets of the lightsail instance.
    Value: !Ref SecretsPolicy
    Export:
      Name: !Sub lightsail-${AWS::Region}-${InstanceName}-SecretsPolicyArn

Resources:

  InstanceKeyPair:
    Type: Custom::LightsailKeyPair
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-lightsail-key-pair
      KeyPairName: !Sub lightsail-key-pair-${InstanceName}

  InstanceKeyPairParam:
    Type: Custom::SecureStringParameter
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-secure-string-parameter
      Name: !Sub /lightsail/${InstanceName}/private-key
      Description: !Sub Private Key for the lightsail key pair for instance ${InstanceName}
      Type: SecureString
      Value: !GetAtt InstanceKeyPair.PrivateKey

  StaticIp:
    Type: Custom::LightsailStaticIp
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-lightsail-static-ip
      StaticIpName: !Sub lightsail-static-ip-${InstanceName}

  Instance:
    Type: Custom::LightsailInstance
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-lightsail-instance
      InstanceName: !Ref InstanceName
      KeyPairName: !Ref InstanceKeyPair
      StaticIpName: !Ref StaticIp

  User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub lightsail-user-${AWS::Region}-${InstanceName}
      Tags:
        - Key: LightsailInstance
          Value: !Ref InstanceName
  UserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: 0
      UserName: !Ref User
  AccessKeyParameter:
    Type: Custom::SecureStringParameter
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-secure-string-parameter
      Name: !Sub /lightsail/${InstanceName}/access-key
      Description: !Sub Access Key ID for the lightsail user for instance ${InstanceName}
      Type: SecureString
      Value: !Sub '{"accessKeyId":"${UserAccessKey}","secretAccessKey":"${UserAccessKey.SecretAccessKey}"}'
  SecretsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub lightsail-${InstanceName}-secrets-policy
      Description: !Sub Grants permissions to protected elements of the ${InstanceName} Lightsail instance.
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: ssm:GetParameter*
            Resource:
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/lightsail/${InstanceName}/private-key'
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/lightsail/${InstanceName}/access-key'