Version: master
Template: custom-resource
AppName: lightsail-docker-compose
Regions:
  - us-east-1
PreBuild: |
  pushd ../.. && npm ci && popd && \
  npx tsc -b && npx ncc build src/index.ts -mo dist && cp schema.json dist && \
  cd dist && npm init -y >/dev/null

Parameters:
  Name: lightsail-docker-compose
  Runtime: nodejs14.x
  Handler: index.handler
  CodeDir: './dist'
Substitution:
  PolicyStatements:
    - Effect: Allow
      Action:
        - lightsail:GetInstance
      Resource: 
        Fn::Sub: arn:aws:lightsail:*:${AWS::AccountId}:*
