#!/bin/bash

# Uploads the lambda function for all custom resources in the lambda/custom-resource directory
# Then deploys

VERSION="$1"

if [[ -z "$VERSION" ]]; then
    echo "usage: $(basename "$0") <version-number>"
    exit 1
fi

DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "$DIR/../lambda/custom-resource"

BUCKET=$(aws ssm get-parameter --name ' /global/bucket-name' --output text --query 'Parameter.Value')
PIDS=
for PACKAGE in *; do
    if [[ -e "$PACKAGE/requirements.txt" ]]; then
        "$DIR/package-code" "$PACKAGE" "$BUCKET" "$PACKAGE/v$VERSION" \
            "mkdir site-packages 2>/dev/null" \
            "python -m pip install -q -r requirements.txt --target site-packages" &
        PIDS+=" $!"
    elif [[ -e "$PACKAGE/package.json" ]]; then
        "$DIR/package-code" "$PACKAGE" "$BUCKET" "$PACKAGE/v$VERSION" \
            "" "NODE_ENV=production npm ci --silent" &
        PIDS+=" $!"
    else 
        echo "update-custom-resources: no valid packaging command for this directory: $PACKAGE"
    fi
done
for PID in $PIDS; do
    if ! wait $PID; then
        wait
        echo "at least one build has failed - aborting..." > /dev/stderr
        exit 1
    fi
done

cd "$DIR/.."
./bin/cfn-deploy templates/custom-resources.yml custom-resources "CodeVersion=v$VERSION"