name: Publish Release
on:
  push:
    tags:
      - 'v*'

env:
  ROLE: arn:aws:iam::060868188835:role/infra-github-runner

jobs:
  build:
    name: Publish Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm ci
          npm run compile
      - uses: uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: targets/clou-*
          token: ${{ secrets.GITHUB_TOKEN }}
