name: Rotate Lightsail Credentials
on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:
env:
  ROLE: arn:aws:iam::060868188835:role/infra-github-runner
  BASE_DIR: aws/resources

jobs:
  updateFiles:
    name: Get Lightsail Instance Files
    runs-on: ubuntu-latest
    outputs:
      hasFiles: ${{ steps.updateFiles.outputs.hasFiles }}
      fileNames: ${{ steps.updateFiles.outputs.fileNames  }}
    steps:
      - uses: frenck/action-setup-yq@v1
      - uses: actions/checkout@v3
      - id: updateFiles
        name: Get and Update Files
        run: |
          cd "${{ env.BASE_DIR }}"
          LIST=
          for FILE in *; do
          if [[ "$(yq '.Template' < "$FILE")" = lightsail-instance ]]; then
              LIST+=",\"$FILE\""
              SERIAL="$(yq '.Parameters.AccessKeySerial' < "$FILE")"
              NEXT_SERIAL="$(( "$SERIAL" + 1 ))"
              yq -i ".Parameters.AccessKeySerial = $NEXT_SERIAL" "$FILE"
          fi
          done
          LIST="[$(cut -c2- <<< "$LIST")]"
          echo "$LIST"
          echo "::set-output name=hasFiles::$([[ "$LIST" = '[]' ]] && echo false || echo true)"
          echo "::set-output name=fileNames::$(echo "$LIST")"
      - uses: EndBug/add-and-commit@v9.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: github_actions[bot]
          message: 'rotate credentials for lightsail instances'
          push: true

  deployChanges:
    if: needs.updateFiles.outputs.hasFiles == 'true'
    name: Rotate Credentials
    runs-on: ubuntu-latest
    needs:
      - updateFiles
    strategy:
      matrix:
        fileName: ${{ fromJSON(needs.updateFiles.outputs.fileNames) }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: frenck/action-setup-yq@v1
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ env.ROLE }}
      - name: Rotate Access Key for ${{ matrix.fileName }}
        run: |
          ./aws/bin/infra -c "${{ env.BASE_DIR }}/${{ matrix.fileName }}"
