name: Rotate Lightsail Credentials
on:
  # schedule:
  #   - cron: "0 4 * * 1"
  workflow_dispatch:

jobs:
  rotate:
    name: Rotate Lightsail Credentials
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::060868188835:role/infra-github-runner

      - name: Rotate Secrets
        run: |
          PIDS=
          while read STACK; do
              LEN="$(aws cloudformation describe-stack-resources --stack-name "$STACK" --query 'length(StackResources[?ResourceType==`Custom::LightsailInstance`])')"
              if [[ $LEN != 0 ]]; then 
                  NAME="$(aws cloudformation describe-stacks --stack-name "$STACK" --query 'Stacks[0].Parameters[?ParameterKey==`Name`].ParameterValue' | jq -r '.[]' | sed 's@\r@@g')"
                  ./aws/bin/lightsail-deploy "$NAME" rotate-access-key &
                  PIDS+=" $!"
              fi
          done <<< "$(aws cloudformation describe-stacks --query 'Stacks[?starts_with(StackName,`lightsail-`)].StackName' | jq -r '.[]' | sed 's@\r@@g')"
          for PID in $PIDS; do
              if ! wait $PID; then
                  wait
                  echo "at least one instance failed the redeploy - aborting..." >&2
                  exit 1
              fi
          done
